
# This pipeline will:
# - Convert block blobs to page blobs.
# - Create Resource Group.
# - Create Managed Disks.
# - Create Azure VM.
# 
# 
#
# The variables are provided by Variable group with the name: variable_iScaleArchive
#
#
# Pipeline are used with User assigned managed identity
#
# This pipeline also expects Azure (Resource Manager) service connections in Azure DevOps with the name 'connection_snapshottestsa' and 'connection_subscription' , using Workload Identity federation (manual). This service connections must have been set up in the Project Settings.

trigger: none
pr: none

pool:
  name: easec-pool

variables:
- group: variable_iScalaArchive
  

stages:

- stage: convert_block_blobs_to_page_blobs
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'connection_snapshottestsa'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: |
          $Env:AZCOPY_AUTO_LOGIN_TYPE="MSI"
          $Env:AZCOPY_MSI_CLIENT_ID="$(clientId)"
          azcopy copy "$(sourceBlobOsDisk1Snap)" "$(destinationBlobOsDisk1Snap)" --blob-type PageBlob
          azcopy copy "$(sourceBlobDataDisk1Snap)" "$(destinationBlobDataDisk1Snap)" --blob-type PageBlob

- stage: create_resource_group
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'connection_subscription'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: |
          az group create --location "$(rgLocation)" --name "$(resourceGroupName)"

- stage: create_managed_disks
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'connection_snapshot-rg'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: |
          az disk create --resource-group "$(resourceGroupName)" --name "$(osDiskName)" --sku "$(storageType)" --location "$(vmLocation)" --size-gb "$(diskSizeOs)" --source "$(destinationBlobOsDisk1Snap)"
          az disk create --resource-group "$(resourceGroupName)" --name "$(dataDiskName)" --sku "$(storageType)" --location "$(vmLocation)" --size-gb "$(diskSizeData)" --source "$(destinationBlobDataDisk1Snap)"

- stage: create_vm
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'connection_snapshot-rg'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: |
          az vm create --name "$(virtualMachineName)" --resource-group "$(resourceGroupName)" --os-type "$(osType)" --size "$(vmSize)" --enable-agent "true" --attach-os-disk "$(osDiskName)" --attach-data-disks "$(dataDiskName)"
